=== arpanet-black/RedGopher/source/RedGopher/cfg/gophermap.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns:gopher="http://arpanet.black/gopher/files" 
	targetNamespace="http://arpanet.black/gopher/files">

	<!-- COMPLEX TYPES -->
	<xs:complexType name="gophermap">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="info" type="xs:string" />
			<xs:element name="error" type="xs:string" />
			<xs:element name="item" type="gopher:item" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="item">
		<xs:sequence>
			<xs:element name="displayText" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="gopherType" type="gopher:gopherType" minOccurs="0" maxOccurs="1" default="BINARY_FILE" />
			<xs:element name="resourceType" type="gopher:resourceType" minOccurs="0" maxOccurs="1" default="LOCAL_FILE" />
			<xs:element name="server" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="port" type="xs:integer" minOccurs="0" maxOccurs="1" />
			<xs:element name="gopherPath" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="parentPath" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="resourcePath" type="xs:string" minOccurs="0" maxOccurs="1" />			
			<xs:element name="content" type="xs:base64Binary" minOccurs="0" maxOccurs="1" />
			<xs:element name="persistent" type="xs:boolean" minOccurs="0" maxOccurs="1" default="false" />
			<xs:element name="directoryContents" type="gopher:directoryContents" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="directoryContents">
		<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="info" type="xs:string" />
			<xs:element name="error" type="xs:string" />
			<xs:element name="item" type="gopher:item" />
		</xs:choice>
	</xs:complexType>
	
	<!-- ENUMERATIONS -->
	<xs:simpleType name="gopherType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="TEXT_FILE" />
			<xs:enumeration value="DIRECTORY" />
			<xs:enumeration value="CSO_SEARCH" />
			<xs:enumeration value="ERROR" />				
			<xs:enumeration value="BINHEX_ENCODED" />
			<xs:enumeration value="BIN_ARCHIVE" />
			<xs:enumeration value="UNIX_UUENCODED" />
			<xs:enumeration value="INDEX_SEARCH_SERVER" />
			<xs:enumeration value="TELNET" />
			<xs:enumeration value="BINARY_FILE" />
			<xs:enumeration value="REDUNDANT_SERVER" />
			<xs:enumeration value="TN3270_SESSION" />
			<xs:enumeration value="GIF_GRAPHICS_FILE" />
			<xs:enumeration value="PNG_IMAGE_FILE" />
			<xs:enumeration value="IMAGE_FILE" />
			<xs:enumeration value="INFORMATION_TEXT" />
			<xs:enumeration value="HTML" />
			<xs:enumeration value="AUDIO" />
			<xs:enumeration value="NONE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="resourceType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LOCAL_FILE" />
			<xs:enumeration value="LOCAL_DIRECTORY" />
			<xs:enumeration value="VIRTUAL_FILE" />
			<xs:enumeration value="VIRTUAL_DIRECTORY" />
			<xs:enumeration value="RSS2_FEED" />			
		</xs:restriction>
	</xs:simpleType>

	<!-- DOCUMENT ROOT ELEMENT -->
	<xs:element name="gophermap" type="gopher:gophermap"/>
	
</xs:schema>

=== arpanet-black/RedGopher/source/RedGopher/gopher/gophermap.xml
<?xml version="1.0" encoding="UTF-8"?>
<gopher:gophermap xmlns:gopher="http://arpanet.black/gopher" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://arpanet.black/gopher gophermap.xsd ">
  
  <info>Welcome to RedGopher</info>
  <!-- <error>Oops.</error> -->
  <info></info>
  
  <info>A File Resource Example</info>
  <item>
    <displayText>A Resource Text File</displayText>
    <gopherType>TEXT_FILE</gopherType>
    <resourceType>LOCAL_FILE</resourceType>
    <gopherPath>gopherPath</gopherPath>
    <resourcePath>resource.txt</resourcePath>
  </item>

  <info>A Directory Resource Example</info>
  <item>
    <displayText>A Sub-Directory</displayText>
    <gopherType>DIRECTORY</gopherType>
    <resourceType>LOCAL_DIRECTORY</resourceType>
    <resourcePath>/images</resourcePath>
  </item>
  
  <info>A BLOB Resource Example</info>
  <item>
    <displayText>A BLOB</displayText>
    <gopherType>TEXT_FILE</gopherType>
    <resourceType>VIRTUAL_FILE</resourceType>
    <gopherPath>testfile.txt</gopherPath>
    <content>This is a test!
    Can it do 2 lines??</content>    
  </item>
  
  <info>A Virtual File Resource Example</info>
  <item>
    <displayText>A BLOB</displayText>
    <gopherType>TEXT_FILE</gopherType>
    <resourceType>VIRTUAL_FILE</resourceType>
    <gopherPath>testfile2.txt</gopherPath>
    <content>this is crazy</content>    
  </item>
  
  <info>An RSS2 Feed Resource Example</info>
  <item>
    <displayText>VC Fed Appple II Forums RSS</displayText>
    <gopherType>DIRECTORY</gopherType> <!-- Optional -->
    <resourceType>RSS2_FEED</resourceType>
    <gopherPath>/feeds/vcfed-apple-ii</gopherPath>
    <resourcePath>http://www.vcfed.org/forum/external.php?type=RSS2&amp;forumids=20</resourcePath>
  </item>
  
</gopher:gophermap>

=== arpanet-black/RedGopher/source/RedGopher/gopher/images/gophermap.xml
<?xml version="1.0" encoding="UTF-8"?>
<gopher:gophermap xmlns:gopher="http://arpanet.black/gopher/gophermap" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://arpanet.black/gopher/gophermap gophermap.xsd ">
  
  <info>Welcome to RedGopher: Images</info>
  <!-- <error>Oops.</error> -->
  
  <info></info>
  <info>A PNG File Resource Example</info>

  <item>
    <displayText>A PNG Image File</displayText>
	<gopherType>PNG_IMAGE_FILE</gopherType>
	<resourceType>LOCAL_FILE</resourceType>
	<gopherPath>/images/extra/division.png</gopherPath>
	<resourcePath>division.png</resourcePath>
  </item>

  
  <info></info>
  <info>A JPG File Resource Example</info>
  <item>
    <displayText>A JPG Image File</displayText>
    <gopherType>IMAGE_FILE</gopherType>
    <resourceType>LOCAL_FILE</resourceType>
    <gopherPath>/images/funny.jpg</gopherPath>
    <resourcePath>funny.jpg</resourcePath>
  </item>
  
  <info></info>
  <info>A GIF File Resource Example</info>
  <item>
    <displayText>A GIF Image File</displayText>
    <gopherType>GIF_GRAPHICS_FILE</gopherType>
    <resourceType>LOCAL_FILE</resourceType>
    <gopherPath>/images/memory_map.gif</gopherPath>
    <resourcePath>memory_map.gif</resourcePath>
  </item>
  
</gopher:gophermap>
